{{- if and .Values.serviceAccount.admin.create .Values.powerdns.admin.enabled -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ include "powerdns.admin.serviceAccountName" . }}
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
