apiVersion: v1
kind: Service
metadata:
  annotations:
    ignore-check.kube-linter.io/use-namespace: ""
  name: {{ include "powerdns.fullname" . }}-admin
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.admin.type }}
  ports:
    - port: {{ .Values.services.admin.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
    module: admin
