kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "powerdns.fullname" . }}-recursor
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
data:
  recursor.j2: |
    {{- tpl (.Files.Get "backend/recursor.j2") . | nindent 4 }}
  
