{{- if .Values.powerdns.recursor.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "powerdns.fullname" . }}-recursor
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "powerdns.selectorLabels" . | nindent 6 }}
      module: recursor
  endpoints:
  - port: http
    path: /metrics
{{- end -}}