apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}-dnsdist
  labels:
    {{ include "powerdns.labels" . | nindent 4 }}
type: Opaque
data:
    username: {{ .Values.powerdns.dnsdist.webserver.username | b64enc | quote }}
    password: {{ .Values.powerdns.dnsdist.webserver.password | b64enc | quote }}