{{- if .Values.serviceAccount.dnsdist.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ include "powerdns.dnsdist.serviceAccountName" . }}
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.dnsdist.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
