apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
    {{ include "powerdns.labels" . | nindent 4 }}
type: Opaque
data:
    {{- if eq  .Values.powerdns.backend "mysql"}}
    admin_db_url: {{ printf "mysql://%s:%s@%s/powerdnsadmin" (include "powerdns.databaseUser" .)  (include "powerdns.databasePassword" .) (include "powerdns.databaseHost" .) | b64enc | quote }}
    {{- else }}
    admin_db_url: {{ printf "sqlite:////opt/powerdns/powerdnsadmin.db" | b64enc | quote }}
    {{- end }}
