kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ include "powerdns.fullname" . }}-auth
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
data:
  pdns.j2: |
    {{- tpl (.Files.Get "backend/pdns.j2") . | nindent 4 }}
  
