apiVersion: v1
kind: Service
metadata:
  annotations:
    ignore-check.kube-linter.io/use-namespace: ""
  name: {{ include "powerdns.fullname" . }}-auth
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
    module: auth
spec:
  type: {{ .Values.services.auth.type }}
  clusterIP: {{ .Values.services.auth.clusterIP }}
  ports:
    - port: {{ .Values.services.auth.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.services.auth.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.services.auth.apiPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
    module: auth
